services:
  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es3b-users:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/yovi
    depends_on:
      - mongo
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://158.158.17.160:3000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es3b-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es3b-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

volumes:
  mongo_data:

networks:
  monitor-net:
    driver: bridge
